### PR TITLE
Take into account different spec of dired-mark-files-regexp from dired+

### PR DESCRIPTION
**Pull request by yantar92**

### CODE REVIEW

**Comment by mattiasb** [comment]
I'm looking at `dired+` now and it seems like its author basically overwrites functions defined in dired with his own implementations. That's not something I want to support. I'm sorry.

**Comment by yantar92** [comment]
Fair point. I guess, I can also try to approach the author of dired+ to
deal with the problem.

**Comment by mattiasb** [comment]
> Fair point. I guess, I can also try to approach the author of dired+ to deal with the problem.

Yeah. Changing the number of parameters seems invasive. If I remember correctly yesterday it looked like the parameters by default was meant to work like regular dired though. Perhaps it's unintended?

**Comment by yantar92** [comment]
I reported the bug to dired+ author and he fixed it by yesterday ;)

**Comment by mattiasb** [comment]
Yay! :)

**Pull request closed without merging**
